### PR TITLE
fix: Various improvements to the Observations screen 

### LINKED ISSUE #348: Collapse sub-menus by default in Observations
**Describe the idea**
Upon opening the application, the first thing people do is close the sub menus on the left side

**What's your role? Where and how do you currently use the application?**
Dd tech 

**What is your ideal step by step workflow?**
Submenus should be collapsed by default

**Additional context**
This was requested by NGO partners.

### LINKED ISSUE #371: Mapeo crashes when try to edit already filled "Single select" field
**Describe the bug**
In Mapeo Observations screen, if you look at details of an observation that has single select fields already filled in, then if you try and edit these - or what I did was try to delete the word that was there by placing cursor at the end of the content and hitting backspace, then Mapeo screen went blank and only way I could get it back was to quit and reopen Mapeo. 

**Can you do the same thing twice?**
I did it twice
The exact steps to see the problem again.

**Expected behavior**
Would expect if you click a field where a single select option was already filled in that it would give you the different options again rather than appear to let you edit the text directly.

**Desktop:**
- version for mac
 - Version [5.3.0-beta.2]

### LINKED ISSUE #372: Differentiated UI for unfilled and noneditable fields in observations detail
**Describe the idea**
When you pull up details of a point in Observations screen, if the field is uneditable (eg. multiselect seems uneditable) then it appears greyed out. If the field doesn't have anything filled in yet then it also appears in grey. Can these be differentiated?

**Have you thought about what it might look like?**
Would expect them to look different, so that it was clearer which ones were simply uneditable, and which ones you could click on and edit. Maybe use different colours or fonts etc. to help with this.

### PR DESCRIPTION
**Pull request by okdistribute**
Updates to the latest react-mapfilter

fix: Allow editing Select Multiple components (fixes #372)
fix: Select one editing should not crash Mapeo (fixes #371)
fix: Collapse sub-menus by defauilt in Observations (fixes #348)
feat: Support `localized` type fields
feat: Support `singleline` text fields

### CODE REVIEW

**Comment by okdistribute** [comment]
@gmaclennan ok great I will update to presets that include this label/value and update it in react-mapfilter

**Comment by okdistribute** [comment]
@gmaclennan fix ready! https://github.com/digidem/react-mapfilter/pull/102

**Comment by gmaclennan** [comment]
Thanks @okdistribute I left a review for some small fixes on the PR. Also spotted another small bug and fixed it: https://github.com/digidem/react-mapfilter/pull/103

**Comment by okdistribute** [comment]
Getting a flow bug here trying to integrate react-mapfilter@3.2.3 --

```
Uncaught /home/okdistribute/dev/mapeo-desktop/node_modules/react-mapfilter/commonjs/ObservationDialog/Select.js:128
): %checks
 ^

SyntaxError: Unexpected token :
``` 

Could it be an already known bug? https://github.com/facebook/flow/issues/8411

**Comment by gmaclennan** [comment]
Yuk what a pain. I checked and this is not being stripped as it should be at build time, and I also tried updating all the babel modules to latest. As a fix I just removed the flow checks for this piece of code and published as `v3.2.4`. This is one area where TypeScript is much better — [type predicates](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types) are more powerful I think than what Flow offers.

**Comment by okdistribute** [comment]
Thanks @gmaclennan !

**Pull request merged**
