### PR TITLE
fix: Mapeo config directory should be removable

### PR DESCRIPTION
**Pull request by okdistribute**
You'd get `EPERM` permissions errors if you tried to remove the Mapeo config directory using `rm -rf ~/.config/Mapeo`

### CODE REVIEW

**Review by gmaclennan — COMMENTED** [review]
Setting permissions to 0777 without user knowledge is not ideal: this folder can contain the sensitive project key. Also best not to make files executable (only directories) and I think `chela` is recursive. Can we modify this to only recursively set directories to u+rwx and files to u+rw and leave group and world permissions the same?

**Comment by okdistribute** [comment]
@gmaclennan why do directories need to be executable?

**Comment by gmaclennan** [comment]
Might be a MacOS thing? But also found this https://unix.stackexchange.com/questions/21251/execute-vs-read-bit-how-do-directory-permissions-in-linux-work

**Comment by okdistribute** [comment]
@gmaclennan how critical is it that files are not executable by the user? It would add a significant amount of code and time right now when I have some other things to work on..

**Comment by gmaclennan** [comment]
I think it's fine. It's a small security risk (it introduces a vector for introducing executable code), but not significant I think.

**Comment by okdistribute** [comment]
Opened an issue for this

**Pull request merged**
